name: "KinD (Kubernetes in Docker) Action"
description: "Easily run a Kubernetes cluster in your GitHub Action"
author: "Engineerd"
inputs:
  version:
    description: "Version of Kind to use (default v0.11.1)"
    default: "v0.11.1"
  config:
    description: "Path (relative to the root of the repository) to a kind config file"
  image:
    description: "Node Docker image to use for booting the cluster"
  name:
    description: "Cluster name (default kind)"
    default: "kind"
  wait:
    description: "Wait for control plane node to be ready (default 300s)"
    default: "300s"
  kubeconfig:
    description: "sets kubeconfig path instead of $KUBECONFIG or $HOME/.kube/config"
  skipClusterCreation:
    description: "If true, the action will not create a cluster, just acquire the tools"
    default: "false"
  skipClusterDeletion:
    description: "If true, the action will not delete the cluster"
    default: "false"
  skipClusterLogsExport:
    description: "If true, the action will not export the cluster logs"
    default: "false"
runs:
  using: "node12"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  post-if: success()
