name: "Build and test Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: npm

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - run: npm test

      - run: npm audit
